### ISSUE TITLE
Support default "code" block of Gutenberg editor

### ISSUE THREAD

**Issue by ctron** [EnlighterJS/Plugin.Gutenberg#10]
The Gutenberg editor seems to have default support for a "code" block. It would be great if EnlighterJS would support this as well. In addition to its own custom block.

**Comment by AndiDittrich** [comment]
Hi @ctron,

thats currently not possible. You can use the generic highlighting of EnlighterJS to highlight a Ggutenberg "Code Block" - but selection of any options is impossible.
