### ISSUE TITLE
< (less then) is shown escaped

### ISSUE THREAD

**Issue by izderadicka** [EnlighterJS/Plugin.Gutenberg#11]
Gutenberg block (rust or generic)
 < is shown escaped as &lf;  see below

```
fn ans() -> Option&lt;u32> {
    Some(42)
}

fn main() -> Result&lt;(), String> {
    if 2 > 1 {
    println!("The answer is {:?}", ans());
    }
    Ok(())
}
```
I do have crayon plugin install if it matters ( and it displays less then correctly in classic block)

**Comment by AndiDittrich** [comment]
Hi @izderadicka ,

i've tried to reproduce your issue but everything works fine within the testing environment

did you disabled crayon before you've started to use Enlighter ? They are not compatible as mentioned in the FAQ! Crayon will take over the EnlighterJS elements.

**WIthout Crayon (EnlighterJS Highlighting)**
![image](https://user-images.githubusercontent.com/1474107/57327231-b3b56080-710e-11e9-9478-bb4d7508e012.png)


**With Crayon enabled**
![image](https://user-images.githubusercontent.com/1474107/57327383-1eff3280-710f-11e9-990d-4a6be27f37e4.png)



best regards, Andi

**Comment by izderadicka** [comment]
Oh, I see now, that's bit unfortunate as I'm using crayon for old posts (pre v. 5), so disabling it is not an straightforward option, as it will require updates of old posts.
Thanks for explanation - is there any possibility for these two to coexist?

**Comment by AndiDittrich** [comment]
you have two options:

1. fix the crayon code that it didn't take over the EnlighterJS elements (it selects all `pre` blocks)
2. convert your legacy posts to EnlighterJS codeblocks (manually or by using an [automatic filter](https://github.com/EnlighterJS/Plugin.WordPress/issues/136))
