### ISSUE TITLE
Not displaying "<" symbol

### ISSUE THREAD

**Issue by MChehab94** [EnlighterJS/Plugin.Gutenberg#15]
I'm using the Gutenberg editor and whenever I have the "<" symbol it's being displayed as &lt; like this:
![Screen Shot 2019-07-23 at 1 50 26 PM](https://user-images.githubusercontent.com/15967307/61706624-371b4100-ad51-11e9-9b7f-4cb3fb2d6e49.png)

I'm using version Version 3.10.0 if that helps

**Comment by AndiDittrich** [comment]
you're using Crayon not EnlighterJS....

The WordPress Enlighter Plugin is **NOT COMPATIBLE** with Crayon ... you have to disable it
