### ISSUE TITLE
El plugin no funciona

### ISSUE THREAD

**Issue by eesquer52** [EnlighterJS/Plugin.Gutenberg#16]
En las pruebas locales (en mi computadora) el plugin funciona de forma correcta. Cuando lo instalo en Internet en un servidor Linux se muestran los códigos de manera correcta, pero no se activa la numeración ni se resaltan los colores de los tags; tampoco se activan los botones de Toogle y Copy

**Comment by AndiDittrich** [comment]
hi @eesquer52 

please use **English or German** for support requests...otherwise i cannot help you...
