### ISSUE TITLE
Is there any hotkey to create block?

### ISSUE THREAD

**Issue by Robotxm** [EnlighterJS/Plugin.Gutenberg#19]
For example, when I press ` for 3 times followed by Enter, there will be a legacy Gutenberg code block. Can I add Enlighter blocks in this way?

**Comment by AndiDittrich** [comment]
caused by the monolithic design of Gutenberg it's currently (as i know) not possible to override the default behaviour - therefore i'm unable to implement a Enlighter highlighting
