### ISSUE TITLE
Code block is badly styled in Gutenberg when using Twenty Twenty with dark background set.

### ISSUE THREAD

**Issue by blueset** [EnlighterJS/Plugin.Gutenberg#23]
1. Code text is white on white background when not focused.
   ![image](https://user-images.githubusercontent.com/553831/75847189-72b6d700-5e19-11ea-9d87-ecb184f28aac.png)
2. Code text is not monospaced even when focused.
   ![image](https://user-images.githubusercontent.com/553831/75847222-8bbf8800-5e19-11ea-9a10-850bccbe9251.png)

This happens when using Twenty Twenty with the theme background set to a dark color.

**Comment by AndiDittrich** [comment]
I assume that everything works as expected when using another theme/non-darkmode ?

**Comment by blueset** [comment]
Yes, I just tested with a bright background on Twenty Twenty, and everything works just fine.

**Comment by blueset** [comment]
As for the font, it is still not using a monospaced one even when the background color is changed.

**Comment by AndiDittrich** [comment]
then this issue is related to the TwentyTwenty editor styles and not the Gutenberg plugin. 

i'm sorry for this but i'm unable to address the issue in a generic way. you can add some additional editor styles which are overriding the theme styles and restoring the default appearance (or a darkmode)
