### ISSUE TITLE
Height of gutenberg blocks and colour for highlighted lines (Atomic).

### ISSUE THREAD

**Issue by ajtruckle** [EnlighterJS/Plugin.Gutenberg#25]
Hi!

Please have a look [here](https://www.publictalksoftware.co.uk/2020/04/25/meeting-schedule-assistant-version-20-1-4-newsletter/). I have two Gutenberg Blocks in that post and I have two questions:

1. Is there any possibility to set the block to a certain height so that it will use a vertical scroll bar? It is not critical - I am just curious.

2. I would be grateful for any help in picking a suitable colour for highlighted lines of code in the Atomic theme.

**Comment by AndiDittrich** [comment]
HI @ajtruckle 

is your first question related to the Gutenberg editor or the codeblocks in your website ?

2. use whatever you wan't - maybe a lighter grey

**Comment by ajtruckle** [comment]
> is your first question related to the Gutenberg editor or the codeblocks in your website ?

The specific page I provided you will was created using Gutenberg Editor block. It is that I refer too.

> 2. use whatever you wan't - maybe a lighter grey

I picked a colour.

**Comment by AndiDittrich** [comment]
sorry i didn't understand your first issue:

1. do you want the limit the Gutenberg codeblock height OR
2. do you want to limit the EnlighterJS codeblock height ?

**Comment by ajtruckle** [comment]
Ah, sorry. I had in mind ability to adjust settings for how it would look as a enlighterjs code block.
