### ISSUE TITLE
Support for anchors

### ISSUE THREAD

**Issue by ajtruckle** [EnlighterJS/Plugin.Gutenberg#26]
For, let us say a "Header" block we can set anchors in the advanced area:

https://ultimateblocks.com/anchor-links-wordpress/

For example:

![anchor](https://user-images.githubusercontent.com/7985331/80286588-2c4c6d00-8724-11ea-82f4-9936c940369d.png)

This feature is not in your code block. It would be handy as I am preparing a email with Mailchimp and my online page has the code but not the email. So I could have added the anchor to drill down to the code. Not critical but would be nice feature to set anchor for the block on the page.

**Comment by AndiDittrich** [comment]
just use a  "hidden" anchor element above the codeblock

**Comment by ajtruckle** [comment]
How do I do that? Sorry! I have done a Google for it and can't find these hidden anchor elements.

**Comment by ajtruckle** [comment]
Got it. Just insert a heading but with no text. And set an anchor.
