### ISSUE TITLE
Support for animated blocks?

### ISSUE THREAD

**Issue by ajtruckle** [EnlighterJS/Plugin.Gutenberg#28]
Hi

I can't remember if I have asked this before. Here is a sample page that has a elighter code block on it:

https://www.publictalksoftware.co.uk/2020/10/meeting-schedule-assistant-version-20-2-8-newsletter/

The website is using an animations plugin. It seemed that I was able to apply a animation to the block, but when it is published the animation doesn't work.

It might not be possible anyway to do,

If you inspect the source of the other blocks they have an animation specified in the class definition.

Not to worry if it can't be done.

**Comment by AndiDittrich** [comment]
In case the animations are created via css3 transforms it should work by adding the class manually to the Enlighter block.

**Comment by ajtruckle** [comment]
At the moment it looks like this:

![Classes](https://user-images.githubusercontent.com/7985331/96140106-7ce49c00-0ef7-11eb-98a6-d371cdee0ec3.png)

I don't know how else to set them.

**Comment by AndiDittrich** [comment]
did you enabled the feature in `Enlighter -> Options -> Advanced -> EnlighterJS -> EnlighterJS options -> Retain CSS Classes` ?

**Comment by ajtruckle** [comment]
I switched that option on and it did the trick! Thanks.
