### ISSUE TITLE
Theme Customizer Background Color

### ISSUE THREAD

**Issue by dannyhanes** [EnlighterJS/Plugin.Gutenberg#3]
Is there any way to change the background color of a theme? I can see where I can change it for the raw output, but I don't see any setting for the theme background color.

**Comment by AndiDittrich** [comment]
Hi Danny,

the issue is related to the EnlighterJS theme engine - not the Gutenberg Editor Plugin.

Just modify/override the css of the theme - setting the background via the customizer is not possible because of the different themes (multiple backgrounds..)

best regards, Andi

**Comment by dannyhanes** [comment]
@AndiDittrich Ah got it. I modified the css for the theme in the plugins folder and it is working now. Thanks!

**Comment by AndiDittrich** [comment]
great! but consider to add the custom classes to your themes css - otherwise they will be removed by the next Enlighter plugin update

**Comment by dannyhanes** [comment]
....not exactly sure how to do that 😆
