### ISSUE TITLE
rangeCount checking is required before calling getRangeAt() in safari.

### ISSUE THREAD

**Issue by phruse** [EnlighterJS/Plugin.Gutenberg#36]
**WordPress Editing Mode**
Gutenberg

**Frontend or Backend Issue**
Backend Issue

**To Reproduce**
when clicking on inline code area is displayed that “This block has encountered an error and cannot be previewed.”.

**Screenshots**
<img width="547" alt="스크린샷 2022-03-09 오전 12 48 35" src="https://user-images.githubusercontent.com/58696810/157273620-381751b1-84e8-43bb-8274-00ded8508cac.png">

**Modify**
resources/gutenberg/enlighterjs.gutenberg.min.css
```
... ,t=e&&e.getRangeAt(0), ...
```
to
```
... ,t=e&&e.rangeCount>0&&e.getRangeAt(0), ...
```

Now it will work in safari! 😄

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: safari
 - Version: 15.2

**Comment by AndiDittrich** [comment]
thanks @phruse 

i'll check this soon
