### ISSUE TITLE
Highlight context menu item

### ISSUE THREAD

**Issue by ajtruckle** [EnlighterJS/Plugin.Gutenberg#39]
Hi

This is a stab in the dark!

Please see:

https://wordpress.org/support/topic/colour-of-hyperlink-in-info-box-2/#post-15717252

The plugin vendor says I should click "Highlight". But I do not see that. All I see is "Enlighter JS...".

Can you shed any light on that?

Thank you.

**Comment by AndiDittrich** [comment]
nothing related to Enlighter Gutenberg. the list your referring contains all registered inline editor styles. maybe a cache issue or an outdated 3rd party plugin as mentioned in the linked thread
