### ISSUE TITLE
Knowing if EnlighterJS is used on page?

### ISSUE THREAD

**Issue by robbelroot** [EnlighterJS/Plugin.Gutenberg#40]
Hey guys,

I wanted to know, if there is any kind of possibility, to know if a gutenberg enlighter block is used on a page?

I tried finding out, which blocks/shortcodes you've defined, but had no success, I tried like:
```
global $post;
  // has_shortcode($post->post_content, 'enlighter')
  if (is_a($post, 'WP_POST') && has_block('enlighter-gutenberg', $post)) {
    echo 'true!';
  } else {
    echo 'nope';
  }
```

Any tips for me?

EDIT: Just when I was about to give up, I found the code block name inside the html and got it to work:
`enlighter/codeblock`

Feel free to delete this..

**Comment by AndiDittrich** [comment]
`has_blocks` should work fine using the correct block names - see https://github.com/EnlighterJS/Plugin.Gutenberg/blob/master/src/EnlighterJS.Gutenberg.js

btw. this only work for Gutenberg content - other content types (transform filters, shortcodes, tinymce, ...) won't be detected. Maybe the js code of the DRI detection may help
