### ISSUE TITLE
Comment block does not translate correctly

### ISSUE THREAD

**Issue by TheBrianGraf** [EnlighterJS/Plugin.Gutenberg#7]
using code (working currently with PowerShell), the '<#' does not translate correctly, so the following code:

function Save-InternetFile {
    <#
        .NOTES
     #>

Appears as:

function Save-InternetFile {
    &lt;#
        .NOTES
     #>

**Comment by AndiDittrich** [comment]
Hi @vtagion ,

i cannot see any difference in the examples you've posted above.
which EnlighterJS version do you use ? Powershell support is only available in v3 which is not part of the WordPress Plugin

**Comment by TheBrianGraf** [comment]
Apologies, 
It appears github translates correctly :)
'<#' is coming through as '& l t ; #' <remove spaces>
the '#>' translates correctly.

anything I can do to help do support PowerShell again? Happy to contribute if I can

**Comment by AndiDittrich** [comment]
hm...i cannot reproduce your issue. 

- which EnlighterJS/Enlighter WordPress Plugin version do you use ?
- in which context does the error appear (workflow) ?

-------------------------

### EnlighterJS 3 PowerShell Example ###

**code used to create the highlighting (raw html)**
![image](https://user-images.githubusercontent.com/1474107/54895510-2f8d7d80-4ec0-11e9-9283-b67d26bea8e5.png)

**result**
![image](https://user-images.githubusercontent.com/1474107/54895541-4cc24c00-4ec0-11e9-8e79-a708389369d3.png)
